services:
  react_workspace:
    container_name: react_workspace
    stdin_open: true
    tty: true
    build:
      args:
        CONTAINER_USER: "${DOCKER_USER}"
      dockerfile: react.dockerfile.dev
    image: react_workspace
    volumes:
      - "${HOME}/.ssh:/home/${DOCKER_USER}/.ssh:ro"
      - "${HOME}/projects:/home/${DOCKER_USER}/development:rw"
    networks:
      - docker_network
    ports:
      - 6060:80

networks:
  docker_network:
    name: docker_network
    driver: bridge
