services:
  go_workspace:
    container_name: go_workspace
    stdin_open: true
    tty: true
    build:
      args:
        CONTAINER_USER: "${DOCKER_USER}"
      dockerfile: ./workspace/go.dockerfile.dev
    image: go_workspace
    volumes:
      - "${HOME}/.ssh:/home/${DOCKER_USER}/.ssh:ro"
      - "${HOME}/projects:/home/${DOCKER_USER}/development:rw"
    networks:
      - docker_network

  go_nginx:
    container_name: go_nginx
    build:
      dockerfile: ./nginx/nginx.dockerfile.dev
    image: go_nginx
    volumes:
      - "${HOME}/projects:/var/www/html:ro"
    ports:
      - 9090:80
    networks:
      - docker_network

networks:
  docker_network:
    name: docker_network
    driver: bridge
