services:
  dotnet_workspace:
    container_name: dotnet_workspace
    stdin_open: true
    tty: true
    build:
      args:
        CONTAINER_USER: "${DOCKER_USER}"
      dockerfile: dotnet.dockerfile.dev
    image: dotnet_workspace
    volumes:
      - "${HOME}/.ssh:/home/${DOCKER_USER}/.ssh:ro"
      - "${HOME}/projects:/home/${DOCKER_USER}/development:rw"
    networks:
      - dotnet_network

networks:
  dotnet_network:
    name: dotnet_network
    driver: bridge
