services:
  go_workspace:
    container_name: go_workspace
    stdin_open: true
    tty: true
    build:
      args:
        CONTAINER_USER: "${DOCKER_USER}"
      dockerfile: go.dockerfile.dev
    image: go_workspace
    volumes:
      - "${HOME}/.ssh:/home/${DOCKER_USER}/.ssh:ro"
      - "${HOME}/projects:/home/${DOCKER_USER}/development:rw"
    networks:
      - go_network

networks:
  go_network:
    name: go_network
    driver: bridge
